{
 "title": "cdevents activity",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" },
   {
    "name": "subjects",
    "label": "subjects",
    "query": "SELECT DISTINCT \"subject\" FROM \"cdevents_lake\" WHERE \"subject\" LIKE '$__searchFilter' AND $__timeFilter(imported_at)"
   },
   {
    "name": "predicates",
    "label": "predicates",
    "query": "SELECT DISTINCT \"predicate\" FROM \"cdevents_lake\" WHERE \"predicate\" LIKE '$__searchFilter' AND subject IN ($subjects) AND $__timeFilter(imported_at)"
   },
   { "name": "pageSize", "label": "pageSize", "query": "10" },
   { "name": "pageIndex" },
   { "name": "offset", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "How many events?",
   "type": "marcusolsson-dynamictext-panel",
   "description": "Count by Subject & Predicate over the time window",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as count, subject, predicate\nFROM cdevents_lake\nWHERE $__timeFilter(timestamp)\n  AND subject = ANY(ARRAY[${subjects:sqlstring}]::text[]))\n  AND predicate = ANY(ARRAY[${predicates:sqlstring}]::text[]))\nGROUP BY subject, predicate\nORDER BY subject, predicate"
    }
   ]
  },
  {
   "title": "Events By Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1 hour', timestamp) AS time,\n  concat(subject,'.', predicate) AS kind,\n  COUNT(*)\nFROM cdevents_lake \nWHERE $__timeFilter(timestamp)\n  AND subject = ANY(ARRAY[${subjects:sqlstring}]::text[]))\n  AND predicate = ANY(ARRAY[${predicates:sqlstring}]::text[]))\nGROUP BY time, kind\nORDER BY time, kind"
    }
   ]
  },
  {
   "title": "How many sources?",
   "type": "marcusolsson-dynamictext-panel",
   "description": "Count by Context'source over the time window",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as count, \"payload\" -> 'context' ->> 'source' as \"context_source\"\nFROM cdevents_lake\nWHERE $__timeFilter(timestamp)\n  AND subject = ANY(ARRAY[${subjects:sqlstring}]::text[]))\n  AND predicate = ANY(ARRAY[${predicates:sqlstring}]::text[]))\nGROUP BY context_source\nORDER BY context_source\n"
    }
   ]
  },
  {
   "title": "Events Logs",
   "type": "volkovlabs-table-panel",
   "description": "List the ${limit} first events",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\",\n  \"subject\",\n  \"predicate\",\n  \"payload\" -> 'subject' as \"payload_subject\",\n  \"payload\" -> 'context' as \"payload_context\",\n  \"imported_at\"\nFROM\n  cdevents_lake\nWHERE\n  $__timeFilter(timestamp)\n  AND subject = ANY(ARRAY[${subjects:sqlstring}]::text[]))\n  AND predicate = ANY(ARRAY[${predicates:sqlstring}]::text[]))\nORDER BY\n  imported_at DESC\nLIMIT\n  ${pageSize}\nOFFSET\n  ${offset}"
    },
    {
     "rawSql": "SELECT\n  count(*)\nFROM\n  cdevents_lake\nWHERE\n  $__timeFilter(imported_at)\n  AND ('${subjects:raw}' = '' OR subject IN (${subjects:sqlstring}))\n  AND ('${predicates:raw}' = '' OR predicate IN (${predicates:sqlstring}))"
    }
   ]
  }
 ]
}